version: '2'
services:
  zeek:
    build:
      context: zeek-docker

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build:
      context: kafka-docker
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.178.124"
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.178.124:9200
      #KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      #- ./kafka_folder:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
