apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "$(MY_POD_IP)"
            - name: KAFKA_PORT
              value: "9092" 
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name:  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          image: wurstmeister/kafka
          name: kafka
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
