apiVersion: v1
kind: PersistentVolume
metadata:
  name: zeek-logs
  labels:
    type: local
    volume: zeek-logs
spec:
  storageClassName: manual 
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/zeek-logs" 
