version: '2'
services:
  zeek:
    build:
      context: zeek-docker
    environment:
      KAFKA_HOST: ${MY_IP_ADDRESS}
      KAFKA_PORT: '9092'
      KAFKA_TOPIC: 'zeek'
      TZ: 'Europe/Berlin'
    network_mode: host

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
 
 
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${MY_IP_ADDRESS}
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.178.124:9200
      #KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafkafolder:/kafka
      - /var/run/docker.sock:/var/run/docker.sock

  broai:
    depends_on:
      - zeek
      - zookeeper
      - kafka
    build:
      context: broai-docker
    environment:
      PROJECT_BRANCH: 'david_udacity_project_blue'
      KAFKA_HOST: 'broai_compose_kafka_1'
      KAFKA_PORT: '9092'
      KAFKA_TOPIC: 'zeek'
    ports:
      - 8050:8050
