apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../broai_compose/docker-compose.kafka.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: broai-blue
  name: broai-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broai-blue
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../broai_compose/docker-compose.kafka.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: broai-blue
    spec:
      containers:
        - env:
            - name: KAFKA_HOST
              value: kafka
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_TOPIC
              value: zeek
            - name: PROJECT_BRANCH
              value: david_udacity_project_blue
          image: herrfeder/broai:latest
          name: broai
          ports:
            - containerPort: 8050
          resources: {}
      restartPolicy: Always
status: {}
