apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../broai_compose/docker-compose.file.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: zeek
  name: zeek
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  externalIPs: 
    - {{EXTERNAL_IP}}
  selector:
    io.kompose.service: zeek
status:
  loadBalancer: {}
