apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../broai_compose/docker-compose.file.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: broai
  name: broai-green
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  externalIPs: 
    - {{EXTERNAL_IP}}
  selector:
    io.kompose.service: broai-green
status:
  loadBalancer: {}
